### ISSUE TITLE
Faire la seconde page

### ISSUE THREAD

**Issue by AntoineVieillard** [TeamGlobe42/Globe42#3]

**Comment by Bichonus** [comment]
Salut Antoine, salut salma, 
J'espère que tout va bien. Je sais pas trop si il y a des discussions sur github donc j'écris ici.
Vous avez réussi à avancer depuis lundi dernier ?  Genre mercredi déjà ? 
Ya qq chose que je peux faire d'ici ou pas ? 
Tschuss

**Comment by AntoineVieillard** [comment]
J'ai fait ce que j'ai posté et j'ai commencé à faire le menu aussi. Je vais l'ajouter sur Github ce soir. 
Dis nous plutôt ce que tu veux compte faire et on te laisse le faire. D'ailleurs je me demandais, pour la deuxième page, on garde le même fichier css, comme ça on peut avoir facilement les paramètres du menu, du fond, etc. Puis on peut ajouter des classes pour les spécificités. Non?
